language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  global:
    LD_PRELOAD=/lib/x86_64-linux-gnu/libSegFault.so
before_install:
  - python --version
  - uname -a
  - lsb_release -a
install:
  - pip install coveralls
  - "python setup.py install"
  - pip install tox-travis
script:
  - tox
  - coverage run --source aacgmv2 -m pytest
after_sucess: coveralls
notifications:
  email:
    on_success: never
    on_failure: always